### ISSUE TITLE
How could I use this in developer visual mode? Thank you

### ISSUE THREAD

**Issue by caitakan** [Microsoft/PowerBI-visuals-TableSorter#26]
Tried to use this in developer visual mode but it doesnt work

**Comment by caitakan** [comment]
I use 'pbiviz start' but it doesn't work

**Comment by darthtrevino** [comment]
These visuals have been built outside of the pbiviz-cli ecosystem, so they don't have a developer mode built in. There should be an `npm run build` task that will bundle the visual up for you, and then you can use your browser's debugging facilities to play with the internals. You'll need to generate a fresh build whenever you update though.

**Comment by stopyoukid** [comment]
The command to build has been changed to `npm test`, the README hasn't been updated since we are in the process of transitioning to a new build system.
