### ISSUE TITLE
Limit of 1000 rows

### ISSUE THREAD

**Issue by LameSpy** [Microsoft/PowerBI-visuals-TableSorter#39]
It is very cool visual but it has one problem. There is a limit of 1000 rows. How can I remove this restriction? I found a line in the code with this parameter, but I can not compile the file into pbiviz. Help me please!

**Comment by stopyoukid** [comment]
Unfortunately there is no way to fully remove the limit, the best you can do is raise it. If you'd like to raise it, change [this file](https://github.com/Microsoft/PowerBI-visuals-TableSorter/blob/f7c8fdefd73b8f10b65d37798c20b6132a4291b9/packages/tablesorter-powerbi/src/TableSorterVisual.defaults.ts#L25) and [this file](https://github.com/Microsoft/PowerBI-visuals-TableSorter/blob/f7c8fdefd73b8f10b65d37798c20b6132a4291b9/packages/tablesorter-powerbi/capabilities.json#L44) to be a higher number, say 5000.  Finally, in [this file](https://github.com/Microsoft/PowerBI-visuals-TableSorter/blob/f7c8fdefd73b8f10b65d37798c20b6132a4291b9/packages/tablesorter-powerbi/pbiviz.json#L5), change the number at the end to be a different number (doesn't matter what number) to mark it as a custom build.

Now, you said you can not compile the file into the pbiviz.  Did you follow the instructions at the root of the repo [here](https://github.com/Microsoft/PowerBI-visuals-TableSorter/blob/f7c8fdefd73b8f10b65d37798c20b6132a4291b9/README.md#usage)? If so, are there errors that are being reported?

**Comment by LameSpy** [comment]
1) Download all these files http://joxi.ru/Dr8ZOKVCkoQ8N2
2) I act on this instruction http://joxi.ru/LmGJ0VvcRwqoJr
-I use the code "yarn" and download everything from the repository http://joxi.ru/D2PJ0jvcdqGVXr

I launch yarn test and these errors appear http://joxi.ru/4Ak593jHMovwdm
http://joxi.ru/V2V4gnjC0d9gXr
On this I stopped. Help me please. I've already tried everything

**Comment by stopyoukid** [comment]
So, it seems that some of the commands require git, try installing git first and then running `yarn test`.   You can get git from here: https://git-scm.com/download/win.

**Comment by LameSpy** [comment]
Now i got this error http://joxi.ru/Dr8ZOKVCkMDgq2
I tried to run npm run test but it did not help

**Comment by stopyoukid** [comment]
So, it looks like you're building the 0.10.9 tag. If so, that had some windows build issues. You'll need to apply these fixes first: [here](https://github.com/Microsoft/PowerBI-visuals-TableSorter/commit/a31e3123ba82eecf4e78275ed2cff3fd42046bf4).  Otherwise, you should be able to use the "develop" branch, and compile that.

**Comment by LameSpy** [comment]
Now I downloaded the version for developers http://joxi.ru/KAgeXKjfgKOlVm. I ran the yarn, 
downloaded all the dependencies, 
then I used the yarn test command. 
There is such an error http://joxi.ru/bmoL9ojtMylZn2

**Comment by stopyoukid** [comment]
Ok, I've run into this one before, there is an issue with npm.  Remove the `packages/tablesorter-powerbi/package-lock.json` file ~~as well as the `packages/tablesorter/package-lock.json` files~~, and run `yarn test` again

** __EDIT__ **
Just the one in tablesorter-powerbi.  I've gone ahead and removed it from the repo.

**Comment by LameSpy** [comment]
Now everything is okay, but I did not create a folder tablesorter / powerbi / dist where the file would be pbiviz :( http://joxi.ru/nAykMzRuXwGXVm

**Comment by stopyoukid** [comment]
Great, glad it compiled for you.  OK, so that path isn't quite right, check in `packages/tablesorter-powerbi/dist` , there should be a pbiviz somewhere in that folder.

**Comment by LameSpy** [comment]
I do not have this folder http://joxi.ru/nAykMzRuXwGXVm

**Comment by stopyoukid** [comment]
Hmm, this is very bizarre. Lets try this from scratch.  Here are the commands that I ran, and it produced a pbiviz in that folder, would you mind running it yourself?

```
git clone https://github.com/Microsoft/PowerBI-visuals-TableSorter.git
cd PowerBI-visuals-TableSorter
yarn
yarn test
```

**Comment by LameSpy** [comment]
I have succeeded! Thank you very much!

**Comment by asifm** [comment]
@stopyoukid I'm not having any luck. Getting stuck at `yarn` — the third step of the four above. Thanks for any help in sorting this out.
```
[-/3] ⢀ waiting...
error C:\Users\mehedia\Dropbox\0_Programming_viz_analysis\Power_BI\PowerBI-visuals-TableSorter\node_modules\electron-prebuilt: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\Users\...\Power_BI\PowerBI-visuals-TableSorter\node_modules\electron-prebuilt
Output:
C:\Users\...\Power_BI\PowerBI-visuals-TableSorter\node_modules\electron-prebuilt\install.js:22
  throw err
  ^
```
